# Generated by Django 5.2.7 on 2026-01-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='properties/')),
            ],
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
