# Generated by Django 5.2.7 on 2026-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_property_alter_login_tbl_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reg_tbl',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
