# Generated by Django 5.2.7 on 2026-01-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_property_lat_property_lng_alter_property_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg_tbl',
            new_name='Register',
        ),
        migrations.DeleteModel(
            name='login_tbl',
        ),
    ]
