# Generated by Django 5.2.7 on 2026-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0005_rename_reg_tbl_register_delete_login_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('House', 'House'), ('Flat', 'Flat'), ('Land', 'Land')], default='Villa', max_length=20),
        ),
    ]
