# Generated by Django 5.2.7 on 2026-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0006_property_area_property_bedrooms_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('House', 'House'), ('Land', 'Land')], default='Villa', max_length=20),
        ),
    ]
