# Generated by Django 5.2.7 on 2026-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0009_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
